apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.tenant.polinhou.dev
spec:
  group: tenant.polinhou.dev
  names:
    kind: Tenant
    listKind: TenantList
    plural: tenants
    singular: tenant
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: Tenant is the Schema for the tenants API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: TenantSpec defines the desired state of Tenant
              properties:
                namespace:
                  description: Namespace is the name of the namespace to be created
                  type: string
                resourceQuota:
                  description: ResourceQuota defines the ResourceQuota to be applied to the namespace
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                managed:
                  description: Managed determines if the operator should actively manage and reconcile the resources
                  type: boolean
              required:
              - namespace
              type: object
            status:
              description: TenantStatus defines the observed state of Tenant
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
