apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-operator.serviceAccountName" . }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tenant-operator.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tenant.polinhou.dev"]
    resources: ["tenants"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tenant.polinhou.dev"]
    resources: ["tenants/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tenant-operator.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tenant-operator.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
